### ISSUE TITLE
CSL-JSON export significantly differs between web API and Zotero client

### ISSUE THREAD

**Issue by salim-b** [zotero/dataserver#119] opened 2022-03-01 12:59 UTC
# Problem

Consider the following public Zotero item for all that follows:

<https://www.zotero.org/groups/4603023/zoterro_testing/items/KC6WFG78>

When exporting that item via the Zotero desktop client v5.0.96.3 ([Flatpak version](https://flathub.org/apps/details/org.zotero.Zotero) on Ubuntu 20.04) as `CSL JSON`, the following JSON file is created:

<details><summary>CSL-JSON export via Zotero desktop:</summary>

```json
[
	{
		"id": "ZoteroWebAPI2021",
		"type": "webpage",
		"abstract": "dev:web api:v3:basics",
		"container-title": "Zotero Documentation",
		"language": "en",
		"title": "Zotero Web API Documentation",
		"URL": "https://www.zotero.org/support/dev/web_api/v3/basics",
		"accessed": {
			"date-parts": [
				[
					"2022",
					2,
					20
				]
			]
		},
		"issued": {
			"date-parts": [
				[
					"2021",
					11,
					5
				]
			]
		},
		"citation-key": "ZoteroWebAPI2021"
	}
]
```

</details>

But when I export the same item via [Zotero's web API v3](https://www.zotero.org/support/dev/web_api/v3/start), different JSON content is returned:

<details><summary>CSL-JSON export via Zotero web API:</summary>

```json
{
    "items": [
        {
            "id": "12047273/KC6WFG78",
            "type": "webpage",
            "title": "Zotero Web API Documentation",
            "container-title": "Zotero Documentation",
            "abstract": "dev:web api:v3:basics",
            "URL": "https://www.zotero.org/support/dev/web_api/v3/basics",
            "note": "Citation Key: ZoteroWebAPI2021",
            "language": "en",
            "issued": {
                "date-parts": [
                    [
                        2021,
                        11,
                        5
                    ]
                ]
            },
            "accessed": {
                "date-parts": [
                    [
                        2022,
                        2,
                        20
                    ]
                ]
            }
        }
    ]
}
```

</details>

API call (HTTP GET):

```url
https://api.zotero.org/groups/4603023/items/KC6WFG78?format=csljson
```

The main differences/issues of the web API export are:

1. The items are wrapped in an additional `{"items": ...}` JSON  object. This is annoying.

2. The `citation-key` field ([introduced with CSL 1.0.2](https://github.com/citation-style-language/schema/commit/0f8a9554c784337d26bc017f6c8b2be8bd5a177a)) is missing. This is IMHO critical.

3. To populate the `id` field, some internal Zotero identifier (an integer plus the [`itemKey`](https://www.zotero.org/support/dev/web_api/v3/basics#items)) is used instead of the *citation key* (internally stored in Zotero's `Extra` field).

In combination, 2) and 3) render the resulting JSON useless for software like Pandoc.

Only 3) in isolation would be fine I guess, since a) the [convention for CSL-JSON consumers is to only fall back on the `id` when `citation-key` is missing](https://github.com/citation-style-language/schema/issues/243) and b) `id` is actually intended to be used as a globally unique identifier.

# Proposed solution

1\) and 2\) above should be fixed and CSL-JSON export via Zotero's web API should ideally return the exact same result as CSL-JSON export via Zotero desktop.

**Comment by dstillman** [comment] 2022-04-07 22:16
Duplicate of https://github.com/zotero/dataserver/issues/72

For 2, Zotero doesn't have a Citation Key field yet — you're just using Better BibTeX.

For 3, the `id` is a GUID, and there's no reason to expect it to be the citation key.

**Closed by dstillman** 2022-04-07 22:16 UTC

**Comment by salim-b** [comment] 2022-04-08 00:26
> you're just using Better BibTeX

I chose `CSL JSON` as the export format in Zotero, not BBT's `Better CSL JSON`. So the `citation-key` field is still added by BBT, and not core Zotero?

> Zotero doesn't have a Citation Key field yet

I know ... any chance, Zotero will gain a dedicated citation key field in the forseeable future?

**Comment by dstillman** [comment] 2022-04-08 06:41
> So the citation-key field is still added by BBT, and not core Zotero?

It's not Zotero.

> any chance, Zotero will gain a dedicated citation key field in the forseeable future?

Yes, it will, soon.
